export const sideBarData = [
  // 博客
  {
    documentRootPath: "/",
    scanStartPath: "blog",
    resolvePath: "blog/",
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: "title",
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },

  {
    documentRootPath: "/",
    scanStartPath: "interview/Examples",
    resolvePath: "interview/Examples/",
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: "title",
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: "/",
    scanStartPath: "interview/CSS",
    resolvePath: "interview/CSS/",
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: "title",
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: "/",
    scanStartPath: "interview/Algorithm",
    resolvePath: "interview/Algorithm/",
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: "title",
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: "/",
    scanStartPath: "interview/JavaScript",
    resolvePath: "interview/JavaScript/",
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: "title",
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: "/",
    scanStartPath: "interview/ScenarioQuestion",
    resolvePath: "interview/ScenarioQuestion/",
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: "title",
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: "//",
    scanStartPath: "interview/HTML",
    resolvePath: "interview/HTML/",
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: "title",
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
];
